### ISSUE TITLE
Fantia Error 422 when trying to download posts

### ISSUE THREAD

**Issue by Diblox** [KJHJason/Cultured-Downloader-CLI#42]
Hello, I tried downloading a fantia author's posts using the following command:

`cultured-downloader-cli.exe fantia --cookie_file="C:\Users\dbx\Downloads\fantia.jp_cookies.txt" --fanclub_id 314832`

And I got these errors for every posts in the log:

`Cultured Downloader CLI V1.2.1 [ERROR]: 2023/08/13 18:15:18 fantia error 422: failed to get post details for https://fantia.jp/api/v1/posts/2167948`

I also tried using the command with the session id while removing the cookie_file arg and I got the same error.

**Comment by KJHJason** [comment]
Should be fixed in the latest release
