### ISSUE TITLE
[Bug]: Dots in post title causing a bug

### ISSUE THREAD

**Issue by ewz-ewz** [KJHJason/Cultured-Downloader-CLI#44]
### Which Operating System are you running the program on?

Windows

### Program Version

Cultured Downloader CLI V1.2.2

### Steps to reproduce the bug

. \ . \ src >cultured-downloader-cli pixiv --refresh_token="[my token]" --artwork_id 109920652

### Expected behaviour

instead of getting folder, i got this file with smaller file size and with no extension name,
i tested this with only just this  " --artwork_id 109920652 "
it happened not only with this id but some other id too like " --artwork_id 100885659 "

some id work fine and got folder and image 
but some got this file.

* apologize for my poor grammer and spelling *

### What error code did you receive? (If any)

N/A

### Relevant log output (If any)

no error ,everything is find, 

### Screenshots (Optional)

![Screenshot 2023-08-20 173548](https://github.com/KJHJason/Cultured-Downloader-CLI/assets/74660736/4e96ecc3-f417-4be5-a717-6b9b90ac9afa)

**Comment by KJHJason** [comment]
Thanks for the bug report, I managed to pinpoint the bug and it was due to the fact that the post title ends with a "." and Golang treats it as a valid file extension of "."

Hence, this causes the bug in the `getFullFilePath` function and treats it as a valid file path instead of a directory path.

**Comment by KJHJason** [comment]
ok scratch that, it looks like the dots in the post title will result in weird behaviours as `filepath.Ext` function will still return a non-empty string if there are dots in the filepath. 
Therefore, I believe it would be better to just replace all the dots in the posts with something similar like "," before the download function is called.

**Comment by KJHJason** [comment]
Resolved in https://github.com/KJHJason/Cultured-Downloader-CLI/releases/tag/1.2.3
