### ISSUE TITLE
[Bug]: "error opening log file" after formatting pc

### ISSUE THREAD

**Issue by dioporcos** [KJHJason/Cultured-Downloader-CLI#78]
### Which Operating System are you running the program on?

Windows

### Program Version

1.2.2

### Steps to reproduce the bug

1. launch CMD in folder containing the .exe
2. Insert command:
`cultured-downloader-cli fantia --cookie_file="X:\folder1\folder2\cultured-downloader\cookies.txt" --fanclub_id 123456 --page_num "" --gdrive_api_key (myapikey) --auto_solve_recaptcha=false`
3. receive "error opening log file" as response

### Expected behaviour

Program works as intended and asks for recaptcha then begins downloading

### What error code did you receive? (If any)

N/A

### Relevant log output (If any)

2024/02/20 00:49:36 error opening log file: open C:\Users\user\AppData\Roaming\Cultured-Downloader\logs\cultured_downloader-cli_v1.2.2_2024-02-20.log: The system cannot find the path specified.
log file path: C:\Users\user\AppData\Roaming\Cultured-Downloader\logs\cultured_downloader-cli_v1.2.2_2024-02-20.log

**Comment by KJHJason** [comment]
Oops, this is an oversight by me but it has been fixed in the latest commit, https://github.com/KJHJason/Cultured-Downloader-CLI/commit/ecbcae09297e8a8d4ee3e27270cbd428d27e3127

**Comment by KJHJason** [comment]
Resolved in https://github.com/KJHJason/Cultured-Downloader-CLI/releases/tag/1.2.3
