### ISSUE TITLE
Pixiv Fanbox cookie is invalid

### ISSUE THREAD

**Issue by TheLOL003** [KJHJason/Cultured-Downloader-CLI#8]
I am trying to run **.\Cultured-Downloader-CLI.exe -fanbox_session <id> -fanbox_post <post id>** through cmd but I am getting an error: **"Pixiv Fanbox cookie is invalid"**

I've tried closing and opening chrome but I got the same error. I am using the **FANBOXSESSID** option in \<id>. How can I fix this?

**Comment by KJHJason** [comment]
sorry for the late reply, I will get back to your issue soon (probs two weeks later due to exams)

**Comment by KJHJason** [comment]
I've tested it on my end and I am unable to reproduce the error,

Please ensure that you have entered the command in the following format:
```
.\Cultured-Downloader-CLI.exe -fanbox_session <session_id> -fanbox_post "<post_id(s)>"
```

**Comment by KJHJason** [comment]
> I've tested it on my end and I am unable to reproduce the error,
> 
> Please ensure that you have entered the command in the following format:
> 
> ```
> .\Cultured-Downloader-CLI.exe -fanbox_session "<session_id>" -fanbox_post "<post_id(s)>"
> ```
> 
> Please also ensure that the session ID that you have copied from your browser is correct. You can use tools like [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en) to export all your cookies on the website you're on to a text file.

I just a got a notification from Google Chrome that the extension that I suggested contains a malware, hence, it is removed from Chrome Web Store.

More info:
https://www.reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively/
