### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dioporcos** [KJHJason/Cultured-Downloader-CLI#85]
### Which Operating System are you running the program on?

Windows

### Program Version

latest

### Steps to reproduce the bug

Randomly started having this issue

Warning: reCAPTCHA detected for the current Fantia session...
▐⠂       ▌ Solving reCAPTCHA for Fantia...panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1504bcb]

goroutine 1 [running]:
github.com/KJHJason/Cultured-Downloader-CLI/api/fantia.autoSolveCaptcha(0xc00031f9e0)
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/api/fantia/api.go:139 +0x6cb
github.com/KJHJason/Cultured-Downloader-CLI/api/fantia.SolveCaptcha(0xc00031f9e0, 0xe0?)
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/api/fantia/api.go:201 +0xb5
github.com/KJHJason/Cultured-Downloader-CLI/api/fantia.dlFantiaPost(0x1, 0x9d, {0xc00000bb17, 0x7}, 0xc00031f9e0)
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/api/fantia/api.go:250 +0x33b
github.com/KJHJason/Cultured-Downloader-CLI/api/fantia.(*FantiaDl).dlFantiaPosts(0xc000310550?, 0xc00031f9e0)
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/api/fantia/api.go:287 +0xc5
github.com/KJHJason/Cultured-Downloader-CLI/api/fantia.FantiaDownloadProcess(0xc000310550?, 0xc00031f9e0?)
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/api/fantia/fantia.go:21 +0x5a
github.com/KJHJason/Cultured-Downloader-CLI/cmds.init.func1(0xc0006de000?, {0x179454b?, 0x4?, 0x179454f?})
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/cmds/fantia.go:105 +0x42d
github.com/spf13/cobra.(*Command).execute(0x21a83c0, {0xc0006fa820, 0xa, 0xa})
        C:/Users/Admin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x21a8f40)
        C:/Users/Admin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x60?)
        C:/Users/Admin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        E:/Codes/Github Projects/Cultured-Downloader-CLI/src/cultured_downloader.go:19 +0x55

### Expected behaviour

Captcha should be resolved

### What error code did you receive? (If any)

N/A

**Comment by KJHJason** [comment]
Should be resolved in the latest release, let me know if it still occurs.
